### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by genio** [IshtarStar/docker-compose-nginx-phpfpm#5]
First, thanks! This has been helpful in my learning process so far.

When I point to a src point for /var/www/html, my file ownership gets changed to root:nogroup. I can't chown the files on the system because it's mounted read-only. That breaks my app's ability to actually run.

Do you have any material I can read for this or am I being stupid in some unknown-to-me way?

**Comment by IshtarStar** [comment]
Certainly! 

It seems you're encountering a common issue with Docker volumes and file permissions. When you bind mount a host directory into a Docker container (e.g., `/path/on/host` to `/var/www/html`), the files inside the container show under the same user and group as they have on the host. If your Docker image expects the files to be owned by a certain user or group (like `www-data` for many web servers), this can cause problems.

Here are some solutions you might consider:

1. Set the user in the Dockerfile using the `USER` directive. This doesn't fix the actual permission issue but changes the user running the process.
2. Use an entrypoint script that runs at the container's start, correcting the permissions before the main process starts.
```
#!/bin/sh
chown -R www-data:www-data /var/www/html
exec "$@"
```
4. Use Docker's user namespaces feature which allows mapping container user IDs to host user IDs. This is more complex to set up but can resolve file permission issues.
```
services:
    web:
        image: nginx:latest
        user: "1000:1000"
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm 
```
6. Use `docker-compose` overrides to set the `user` to define the user and group for the running service.
7. Distinguish between development and production. In development, you might use local volumes, while in production, you could use baked-in data that doesn't have the permission issue.

I hope these suggestions help you address the problem.

Which operating system do you use?
